[project]
name = "quantum-code-validator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gitpython>=3.1.44",
    "mcp[cli]>=1.8.1",
    "pennylane==0.41.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
