services:
  - type: web
    name: quantum-code-validator
    env: python
    plan: starter
    region: singapore
    repo: https://github.com/Qyusu/quantum-code-validator
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
    autoDeploy: true
