services:
  - type: web
    name: quantum-code-validator
    env: docker
    plan: starter
    region: singapore
    repo: https://github.com/Qyusu/quantum-code-validator
    branch: main
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
