services:
  - type: web
    name: quantum-code-validator
    env: python
    plan: starter
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
    autoDeploy: true
